[package]
name = "day1"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
core = { path = "../../core" }
tokio = { version = "1", features = ["full"] }
log = "0.4.22"